### ISSUE TITLE
libui function uiFontButtonFont() is now requiring two parameters instead of one

### ISSUE THREAD

**Issue by xorceria** [rjopek/hbui#13]
When I try to compile hbui using successfully compiled libui on OS X 10.13 I get this message:

hbmk2: Compiling...
../../../../../../src/fontbutton.c:13:39: error: too few arguments to function call, expected 2, have 1
        hbui_ret( uiFontButtonFont( b ) );
                  ~~~~~~~~~~~~~~~~    ^
/usr/local/libui/ui.h:999:1: note: 'uiFontButtonFont' declared here
_UI_EXTERN void uiFontButtonFont(uiFontButton *b, uiFontDescriptor *desc);
^
/usr/local/libui/ui.h:29:20: note: expanded from macro '_UI_EXTERN'
#define _UI_EXTERN extern
                   ^
1 error generated.

**Comment by rjopek** [comment]
On a recent version of libui, the uiFontButtonFont() function changed
from returning the font info to returning void and passing the font info
into a referenced variable ( the second parameter )

Rafał
