### ISSUE TITLE
README.md: Broken screenshot links

### ISSUE THREAD

**Issue by vszakats** [RJopek/HBUI#6]
Hi Rafał,

These screenshots are referenced from `README.md`, but missing from the repository:
`docs/tutorial/window_window.png`
`docs/tutorial/window_freebsd.png`
~~`docs/tutorial/window_solaris.png`~~

Or maybe the links remained there by mistake.

**Comment by RJopek** [comment]
Hi Viktor,

First, let's talk about Solaris
I have problems with the compilation Harbour under Solaris
It is particularly vital to me tests are equally important for Harbour. I'm counting on your help

```
SunOS solaris 5.11 11.3 i86pc i386 i86pc
gcc (GCC) 4.8.2
```

**Comment by vszakats** [comment]
This leads a bit too far, and with zero Solaris experience it'd be a long shot to fix the whole stack in this space. I suggest raising the issue on devel list if it's Harbour core related. For the time being removing the screenshot URL would be a "good enough" solution.

**Comment by vszakats** [comment]
/solaris @melak is the expert on Solaris and keeping SunOS support alive in Harbour.

Either way it'd be nice to create a separate thread/Issue for that, with any know details about the problem.

**Comment by vszakats** [comment]
Thanks for the Solaris fix. Closing with the comment that the Windows and FreeBSD screenshots are still missing/links broken. It'd be nice to see those working.
